easy_admin:
    site_name: Conference Guestbook

    design:
        menu:
            - { route: 'homepage', label: 'Back to the website', icon: 'home' }
            - { route: 'conference', label: 'Conferences', icon: 'map-marker' }
            - { route: 'comment', label: 'Comments', icon: 'comments' }

    entities:
        # List the entity class name you want to manage
        Conference:
            class: App\Entity\Conference

        Comment:
            class: App\Entity\Comment
            list:
                fields:
                    - author
                    - { property: 'email', type: 'email' }
                    - { property: 'createdAt', type: 'datetime', type_options: { disabled: true } }
                sort: ['createdAt', 'ASC']
                filters: ['conference']
            edit:
                fields:
                    - { property: 'conference' }
                    - { property: 'createdAt', type: 'datetime', type_options: { disabled: true } }
                    - 'author'
                    - { property: 'email', type: 'email' }
                    - text
